In [1]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes

In [6]:
#Import necessary libraries and such for project. And some extra stuff, just in case.
import pandas as pd
import matplotlib
from pandas import DataFrame
import matplotlib.pyplot as plt
import os

In [3]:

bartco_sqft = pd.read_csv('Data_Sources\med_sqft_bartco.csv')

#verify data reads in and print the first five rows)
bartco_sqft.head()

,Day of Year,Year of Period End,Period Begin,Period End,Median Pending Sqft Yoy (tooltip),Median Pending Sqft Yoy,Median Pending Sqft
0,1,2023,12/5/2022,1/1/2023,-10.90%,-11%,"1,802.10"
1,2,2022,12/6/2021,1/2/2022,8.30%,8%,"2,023"
2,5,2025,12/9/2024,1/5/2025,9.90%,10%,"1,771.70"
3,7,2024,12/11/2023,1/7/2024,-18.80%,-19%,"1,612.10"
4,8,2023,12/12/2022,1/8/2023,5.90%,6%,"1,986.10"

Trying to create a function to read, display shape, dispaly data, and drop necessary columns

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2081396263.py, line 2)

:

In [5]:
def process_data(bartco_sqft):
    # Read in the data for the Bartholomew County median square footage by listing
    bartco_sqft = pd.read_csv('Data_Sources\med_sqft_bartco.csv')
    
    # Define the data types 
    print (bartco_sqft.dtypes)

    # Drop unneccessary columns (YOY data)
    bcosqft_clean = bartco_sqft.drop(columns=['Median Pending Sqft Yoy (tooltip)', 'Median Pending Sqft Yoy'])
    
    return bcosqft_clean

In [ ]:
housing_data= pd.read_csv('Data_Sources\county_market_tracker_clean.zip')
housing_data.head()

,period_begin,period_end,table_id,region,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_yoy,inventory,inventory_yoy,sold_above_list,parent_metro_region,parent_metro_region_metro_code,last_updated
0,4/1/2015,4/30/2015,2550,"Bradley County, TN",Tennessee,TN,Condo/Co-op,3,199900.0,NaN,137.957212,NaN,NaN,NaN,3.0,NaN,0.000000,"Cleveland, TN",17420.0,2/10/2025 14:21
1,2/1/2014,2/28/2014,1958,"Dutchess County, NY",New York,NY,Townhouse,13,190250.0,269500.0,133.055161,-0.017109,127.048023,0.062799,21.0,-0.125000,0.000000,"Poughkeepsie, NY",39100.0,2/10/2025 14:21
2,6/1/2023,6/30/2023,1643,"Holt County, MO",Missouri,MO,Single Family Residential,6,75500.0,229500.0,40.810811,-0.724764,120.578231,0.525863,13.0,1.166667,0.000000,Missouri nonmetropolitan area,NaN,2/10/2025 14:21
3,3/1/2015,3/31/2015,1518,"Adams County, MS",Mississippi,MS,All Residential,-1,94900.0,160750.0,70.059310,-0.224828,81.662621,0.217752,57.0,-0.123077,0.181818,"Natchez, MS",35020.0,2/10/2025 14:21
4,2/1/2016,2/29/2016,806,"Washington County, IL",Illinois,IL,Single Family Residential,6,49000.0,76500.0,32.236842,-0.121009,67.222597,-0.260068,57.0,0.212766,0.400000,Illinois nonmetropolitan area,NaN,2/10/2025 14:21

In [ ]:
bartco_sqft = pd.read_csv('Data_Sources\med_sqft_bartco.csv')
claco_sqft = pd.read_csv('Data_Sources\med_sqft_claco.csv')

In [9]:

housing_data = pd.read_csv(os.path.join('Data_Sources\county_market_tracker_clean.zip'), 
                           usecols=['region', 
                                    'state', 
                                    'median_sale_price', 
                                    'median_list_price', 
                                    'median_ppsf'])

housing_data.head()

,region,state,median_sale_price,median_list_price,median_ppsf
0,"Bradley County, TN",Tennessee,199900.0,NaN,137.957212
1,"Dutchess County, NY",New York,190250.0,269500.0,133.055161
2,"Holt County, MO",Missouri,75500.0,229500.0,40.810811
3,"Adams County, MS",Mississippi,94900.0,160750.0,70.059310
4,"Washington County, IL",Illinois,49000.0,76500.0,32.236842

In [ ]:
bartco_sqft.merge(claco_sqft)

Empty DataFrame
Columns: [Day of Year, Year of Period End, Period Begin, Period End, Median Pending Sqft Yoy (tooltip), Median Pending Sqft Yoy, Median Pending Sqft]
Index: []

KeyError: 4