In [2]:
#Import necessary libraries and such for project. And some extra stuff, just in case.
import pandas as pd
import matplotlib
from pandas import DataFrame
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import datetime
import seaborn as sns

In [5]:
#read in housing data 
filtered_cf = pd.read_csv('filtered_cf.csv')
average_ppsf = pd.read_csv('average_ppsf.csv')
average_saleprice = pd.read_csv('average_saleprice.csv')

In [11]:
# Create a bar graph
fig = px.bar(filtered_cf, x='Median Sale Price', y='Period Begin', color='Region', orientation='h', barmode='group',
             title='Median Sale Prices for the last rolling 12 months',
             labels={'Median Sale Price': 'Median Home Price ($)', 'Date': 'Period Begin'},
             height=400)

fig.show()

In [13]:
average_saleprice

             Region  Median Sale Price
0  Clark County, IN           255938.5
1  Floyd County, IN           278450.0

In [17]:
# Create a bar graph
fig = px.bar(average_saleprice, x='Median Sale Price', y='Region', color='Region', barmode='group',
             title='Average Home Sale Price February 2024 - January 2025',
             labels={'Median Sale Price': 'Median Home Price ($)', 'Region': 'County'},
             height=400)

fig.show()

In [18]:
average_ppsf

             Region  Median Ppsf
0  Clark County, IN   163.120663
1  Floyd County, IN   151.948779

In [19]:
# Create a bar graph
fig = px.bar(average_ppsf, x='Median Ppsf', y='Region', color='Region', barmode='group',
             title='Average of Median Price per Square Foot from February 2024 - January 2025 in Southern Indiana',
             labels={'Median Sale Price': 'Median Price per Square Foot Average ($)', 'Region': 'County'},
             height=400)

fig.show()